### ISSUE TITLE
Копирайт в спеке

### ISSUE THREAD

**Issue by xvitaly** [RussianFedora/sublime_text#1]
Господа, не очень хорошо удалять копирайты из спека. Прекрасно видно, что он был взят отсюда: https://github.com/xvitaly/sublrpm

**Comment by Tigro** [comment]
Я брал спек отсюда. https://bugzilla.redhat.com/show_bug.cgi?id=1275411

Но это не проблема. Что добавить в changelog?

**Comment by isage** [comment]
Я так понимаю, под "копирайтом" имеются в виду строчки в ченджлоге?
А можно узнать, под какой лицензией распространяется ваш спек?
И, вы в курсе, что ваши строчки с "копирайтом" в чейджлоге не соответствуют стандарту, ибо в них не указана версия?

**Comment by Vascom** [comment]
@isage , если лицензия не указана, то по условиям Github https://help.github.com/articles/open-source-licensing/ код считается копирайтным, однако его можно смотреть и форкать.
И вот тут непонятно: с форком можно делать всё, что заблагорассудится или как?

@xvitaly Это уже чисто теоретически рассуждаем.

**Comment by Tigro** [comment]
Я готов вписать в  changelog или первой строчкой в спеке любой копирайт по желанию автора.

**Comment by xvitaly** [comment]
@isage, под GPL.

К команде Russian Fedora как раз претензий-то нет никаких ибо это @askarter потёр все строчки в changelog спека.

@Tigro думаю, было бы неплохо добавить то, что прописано в оригинальном спеке https://github.com/xvitaly/sublrpm/blob/master/sublime.spec с добавлением версий разумеется.

**Comment by isage** [comment]
@xvitaly как интересно. А где это указано? А под GPL какой версии?

**Comment by askarter** [comment]
Извиняюсь, буду дома - посмотрю точнее, откуда был взят этот спек.

**Comment by xvitaly** [comment]
@isage GPLv2. Могу добавить в свой репозиторий соответствующий файл с текстом лицензии если нужно.

Теперь вижу проблема решена. Отлично.

**Comment by isage** [comment]
@xvitaly ну вы же понимаете, что если лицензия не указана - действует "дефолтная". И gpl ей ни на гитхабе, ни в FPCA не является. Лицензия должна быть указана в самом spec-файле, например в комментарии первой строчкой. Текст лицензии приложен отдельным файлом. Вас, конечно, никто не заставляет, просто не хочется подобных претензий в будущем.

(на самом деле, учитывая сколько всего в спеке не по гайдлайнам, проще было бы написать его с нуля, but oh well)

**Comment by Tigro** [comment]
В общем закрываю как исправленную:

https://github.com/RussianFedora/sublime_text/commit/ac83685174a795e11be332a7639023fb17ff2efd

**Comment by askarter** [comment]
Видимо, да. Брал когда-то давно у @xvitaly для собственных целей. А потом уже снова залил на github. Ещё раз приношу свои извинения @xvitaly и за принесённые неудобства команде Russian Fedora.
Впредь буду внимательнее.
